### ISSUE TITLE
App: event firehose / chat stream

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-ui#7]
A simple app with high utility would be to create an interface to all data in an REA network which presents events as a time-ordered list, in a conversational UI.

We could mix in a Holochain chat app in the process of doing this and allow participants in the network to comment on and query economic events as they unfold.

**Comment by fosterlynn** [comment]
Nice issue, good to get some simple experimental apps out there.

Thinking a bit ahead: If chat posts are about an event, either the chat post will have to know what event, or we will have to set up some new data structure for that ourselves.  The latter seems most realistic.  Also it could be that we generally will want to support multiple threads per object (event, process, plan, etc.).  So that would require the additional data structure anyhow, something like EconomicEvent > can have multiple Threads > can have multiple chat posts.  May depend on what all data structure the specific chat app already has too.

**Comment by pospi** [comment]
Actually we can just do this fractally... recursion is fun! I am sure there are better things out there now than my [original comments experiment](https://github.com/pospi/holo-threaded-comments/), but it already does everything we need by not defining any data structures at all. It's simply "add a comment over this base URL", and it doesn't care what the base URL is.

Which means all of the above are just "I am looking at this event ID - find me all comments in response to that ID"... substituting "event" with any of those other record types (including comments themselves).

**Comment by almereyda** [comment]
Sourcing and displaying events is nicely exemplified in

- https://miaengiadina.github.io/geopub/
  - https://github.com/miaEngiadina/geopub
  - https://miaengiadina.github.io/openengiadina/

via

- https://socialhub.network/t/collaborative-maps-with-activitypub/164/17

An extreme version is

- https://peripleo.pelagios.org/

Why not reuse the Matrix.org data model or a JSON-LD-context-enhanced derivate for the chat feed? It brings [Event Graphs](https://matrix.org/docs/spec/#event-graphs) that might be extensible in some way, from one implementation to the other.

Is there place for an event Hypergraph combining both GraphQL/RDF worlds with DAGs?

**Comment by pospi** [comment]
@almereyda thanks for the info! Those look like really interesting and worthwhile projects. However I feel the topics you're bringing here are mostly more backend related than UI layer?

So, I can only really comment in terms of the [related Holochain project](https://github.com/holo-rea/holo-rea) we have going on. I did do some comparison of Holochain and ActivityPub early on, and there is no significant reason that HC can't act as a Solid pub other than that they force you to use a JSONRPC interface at present (you don't get low-level HTTP access). The other related thing here is that there are some DAG implementations starting up in Holochain-land, and probably eventually we will be using them for keeping time-ordered lists. But for an MVP this is likely to be a pretty quick and dirty integration that just brings in chunks of content and manually sorts them...

**Comment by fosterlynn** [comment]
Thanks @almereyda for the links!  One small word of caution, we in VF should say "economic event" probably (I am very guilty), because most of the world uses "event" as the thing you go to for a day that has music or workshops, a la [Mobilizon](https://joinmobilizon.org/en/).  That doesn't invalidate the above conversation, just making sure we're talking about the same thing.

**Comment by almereyda** [comment]
Thank you for the clarification, I was indeed mistaken.

I felt also remembered of this conversation, when I compiled the links and summary for [the Web of Needs](https://github.com/valueflows/forum.valueflo.ws/issues/128#issuecomment-578497696), since it apparently realises what is promised here.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-ui/-/issues/7.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
